name: fluent_date_picker
description: A fork of the fluent_ui project date picker.
version: 0.0.1
homepage: https://github.com/ConcenTech/fluent_date_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/AcrylicNoise.png
